/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"


void
calculator_1(host)
char *host;
{
	CLIENT *clnt;
	int  *result_1;
	intpair  addition_1_arg;
	int  *result_2;
	intpair  substraction_1_arg;
	int  *result_3;
	intpair  multiplication_1_arg;
	double  *result_4;
	intpair  division_1_arg;
	clnt = clnt_create(host, CALCULATOR, CALCULATOR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = addition_1(&addition_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = substraction_1(&substraction_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = multiplication_1(&multiplication_1_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	calculator_1( host );
}
