/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
addition_1(argp, rqstp)
	intpair *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
substraction_1(argp, rqstp)
	intpair *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
multiplication_1(argp, rqstp)
	intpair *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

double *
division_1(argp, rqstp)
	intpair *argp;
	struct svc_req *rqstp;
{

	static double  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
