/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;
#ifdef __cplusplus
extern "C" bool_t xdr_intpair(XDR *, intpair*);
#elif __STDC__
extern  bool_t xdr_intpair(XDR *, intpair*);
#else /* Old Style C */
bool_t xdr_intpair();
#endif /* Old Style C */


#define CALCULATOR ((rpc_uint)0x23451111)
#define CALCULATOR_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ADDITION ((rpc_uint)1)
extern "C" int * addition_1(intpair *, CLIENT *);
extern "C" int * addition_1_svc(intpair *, struct svc_req *);
#define SUBSTRACTION ((rpc_uint)2)
extern "C" int * substraction_1(intpair *, CLIENT *);
extern "C" int * substraction_1_svc(intpair *, struct svc_req *);
#define MULTIPLICATION ((rpc_uint)3)
extern "C" int * multiplication_1(intpair *, CLIENT *);
extern "C" int * multiplication_1_svc(intpair *, struct svc_req *);
#define DIVISION ((rpc_uint)4)
extern "C" double * division_1(intpair *, CLIENT *);
extern "C" double * division_1_svc(intpair *, struct svc_req *);

#elif __STDC__
#define ADDITION ((rpc_uint)1)
extern  int * addition_1(intpair *, CLIENT *);
extern  int * addition_1_svc(intpair *, struct svc_req *);
#define SUBSTRACTION ((rpc_uint)2)
extern  int * substraction_1(intpair *, CLIENT *);
extern  int * substraction_1_svc(intpair *, struct svc_req *);
#define MULTIPLICATION ((rpc_uint)3)
extern  int * multiplication_1(intpair *, CLIENT *);
extern  int * multiplication_1_svc(intpair *, struct svc_req *);
#define DIVISION ((rpc_uint)4)
extern  double * division_1(intpair *, CLIENT *);
extern  double * division_1_svc(intpair *, struct svc_req *);

#else /* Old Style C */
#define ADDITION ((rpc_uint)1)
extern  int * addition_1();
extern  int * addition_1_svc();
#define SUBSTRACTION ((rpc_uint)2)
extern  int * substraction_1();
extern  int * substraction_1_svc();
#define MULTIPLICATION ((rpc_uint)3)
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define DIVISION ((rpc_uint)4)
extern  double * division_1();
extern  double * division_1_svc();
#endif /* Old Style C */

#endif /* !_CALCULATOR_H_RPCGEN */
